#!/usr/bin/env python3
"""Generate tools/isa_defs.py, src/isa_defs.vh and docs/isa.md from isa/isa.yaml."""
import argparse, difflib, pathlib, sys
import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "isa" / "isa.yaml"
TARGETS = {"isa_defs.py": ROOT / "tools", "isa_defs.vh": ROOT / "src", "isa.md": ROOT / "docs"}
HEADER = "GENERATED by tools/gen_isa.py from isa/isa.yaml — do not edit by hand."

def load():
    return yaml.safe_load(SRC.read_text())

def gen_python(isa):
    L = ["# " + HEADER, "WORD_BITS = %d" % isa["word_bits"], "PC_BITS = %d" % isa["pc_bits"]]
    for key, name in [("registers", "REGS"), ("flags", "FLAGS"), ("banks_out", "BANK_OUT"), ("banks_in", "BANK_IN"),
                      ("alu_fn", "ALU_FN"), ("br_cond", "BR_COND"), ("waitp_cond", "WAITP_COND"), ("pin_op", "PIN_OP"),
                      ("wait_sub", "WAIT_SUB"), ("time_op", "TIME_OP"), ("classes", "CLASSES"), ("misc_sub", "MISC_SUB")]:
        L.append("%s = %r" % (name, dict(isa[key])))
    L.append("LAYOUTS = %r" % {c: {f: tuple(r) for f, r in flds.items()} for c, flds in isa["layouts"].items()})
    L.append("MNEMONICS = %r" % {m: {"class": s["class"], "fixed": dict(s["fixed"]), "operands": list(s["operands"])} for m, s in isa["mnemonics"].items()})
    L.append("SEMANTICS = %r" % dict(isa["semantics"]))
    return "\n".join(L) + "\n"

def gen_verilog(isa):
    L = ["// " + HEADER, "`ifndef ISA_DEFS_VH", "`define ISA_DEFS_VH"]
    def defs(prefix, table, width):
        for k, v in table.items():
            L.append("`define %s_%s %d'd%d" % (prefix, k, width, v))
    defs("ISA_CLS", isa["classes"], 4); defs("ISA_MISC", isa["misc_sub"], 12); defs("ISA_ALU", isa["alu_fn"], 4)
    defs("ISA_BR", isa["br_cond"], 3); defs("ISA_WAIT", isa["wait_sub"], 3); defs("ISA_WP", isa["waitp_cond"], 2)
    defs("ISA_PIN", isa["pin_op"], 2); defs("ISA_TIME", isa["time_op"], 1); defs("ISA_FLAG", isa["flags"], 5)
    defs("ISA_BANKO", isa["banks_out"], 2); defs("ISA_BANKI", isa["banks_in"], 2)
    L.append("`endif")
    return "\n".join(L) + "\n"

def gen_doc(isa):
    L = ["<!-- %s -->" % HEADER, "# %s v%d instruction set" % (isa["name"], isa["version"]), "",
         "16-bit instructions; class in bits [15:12]. Registers R0–R7, R0 reads as zero.", "",
         "| Mnemonic | Class | Operands (fields) | Fixed fields |", "|---|---|---|---|"]
    for m, s in isa["mnemonics"].items():
        L.append("| `%s` | %s (%d) | %s | %s |" % (m, s["class"], isa["classes"][s["class"]], ", ".join(s["operands"]) or "—",
                                                    ", ".join("%s=%s" % kv for kv in s["fixed"].items()) or "—"))
    L += ["", "## Field layouts", "", "| Class | Fields (msb:lsb) |", "|---|---|"]
    for c, flds in isa["layouts"].items():
        L.append("| %s | %s |" % (c, ", ".join("%s[%d:%d]" % (f, r[0], r[1]) for f, r in flds.items())))
    L += ["", "## Semantics", ""]
    for k, v in isa["semantics"].items():
        L.append("- **%s.** %s" % (k, v))
    return "\n".join(L) + "\n"

def render(isa):
    return {"isa_defs.py": gen_python(isa), "isa_defs.vh": gen_verilog(isa), "isa.md": gen_doc(isa)}

def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--out-dir"); ap.add_argument("--check", action="store_true")
    a = ap.parse_args(); files = render(load()); rc = 0
    for name, text in files.items():
        dest = (pathlib.Path(a.out_dir) / name) if a.out_dir else (TARGETS[name] / name)
        if a.check:
            cur = dest.read_text() if dest.exists() else ""
            if cur != text:
                rc = 1; sys.stdout.writelines(difflib.unified_diff(cur.splitlines(True), text.splitlines(True), str(dest), "generated"))
        else:
            dest.parent.mkdir(parents=True, exist_ok=True); dest.write_text(text); print("wrote", dest)
    sys.exit(rc)

if __name__ == "__main__":
    main()
